### ISSUE TITLE
Empty published package?

### ISSUE THREAD

**Issue by davewasmer** [nodaguti/stylelint-no-unused-selectors#122]
Feeling like I'm missing something obvious here, but it seems like the published package on npm is basically empty. For every published version from 1.0.0 to 1.0.9, there's no `dist` folder in the published tarball, which means this package is unusable unfortunately.

**Comment by nodaguti** [comment]
Thank you for reporting the issue.
Look like something went wrong with our CircleCI settings to publish this package on a weekly basis automatically. I'll look into it soon.

**Comment by davewasmer** [comment]
Looks like your Circle CI config is off. Seems like there's no build step during the release phase, so no `dist` folder is created

**Comment by nodaguti** [comment]
Thank you so much @davewasmer, the config must be fine right now.
Fingers crossed the automatic release will work well next weekend... 🤞 

Also I've just published a new version v1.0.10 so that you can get a fresh, stuffed package 😄

If you still have any problems, please feel free to reopen this issue!

**Comment by davewasmer** [comment]
Thanks @nodaguti! Also, FWIW, looks like your setup with semantic-release. That means it should automatically publish a new version whenever your commit message prefixes indicate that a new version is needed (i.e. you merge something with a `fix:` prefix, it will automatically release a new patch level version), rather than on a calendar-based schedule.
